spring:
  application:
    name:  cdc
  cloud:
    stream:
      bindings:
        practiceSessionOutput:
          destination: practice.session
          binder: rabbit1
      binders:
        rabbit1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
